FROM node:16.15.0 AS ui-build
RUN mkdir -p /ngfrontend
WORKDIR /ngfrontend
COPY package*.json /ngfrontend
RUN npm install
COPY . /ngfrontend
RUN npm install -g @angular/cli
RUN npm run build --prod

#################################################################
FROM node:16.15.0 AS server-build
WORKDIR /root/
COPY --from=ui-build /ngfrontend/dist ./ngfrontend/dist
COPY /backend/package*.json ./
RUN npm install
COPY /backend/server.js .

EXPOSE 3080

CMD ["node", "server.js"]
