apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ng-backend
  name: ng-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-backend
  template:
    metadata:
      labels:
        app: ng-backend
    spec:
      containers:
        - name: ng-backend
          image: (*IMAGE*)
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    svc: ng-svc-backend
  name: ng-svc-backend
spec:
  ports:
    - name: "node-api-port"
      port: 80
      targetPort: 80
  selector:
    app: ng-backend
status:
  loadBalancer: {}
