apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ng-backend
  name: ng-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-backend
  template:
    metadata:
      labels:
        app: ng-backend
    spec:
      containers:
        - name: ng-backend
          image: stmum0107/ngserver:v3
          ports:
            - containerPort: 3002
          resources: {}
      restartPolicy: Always
status: {}
