apiVersion: v1
kind: Service
metadata:
  labels:
    svc: ng-svc-backend
  name: ng-backend
spec:
  ports:
    - name: "node-api-port"
      port: 3001
      targetPort: 3002
  selector:
    app: ng-backend
status:
  loadBalancer: {}
