apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ng-frontend
  name: ng-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-frontend
  template:
    metadata:
      labels:
        app: ng-frontend
    spec:
      containers:
        - name: ng-frontend
<<<<<<< HEAD
          image: stmum0107/ngclient:34
=======
          image: stmum0107/ngclient:33
>>>>>>> 3bc914f77266c564a07da6b73812d15d22e224ca
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    svc: ng-svc-frontend
  name: ng-svc-frontend
spec:
  ports:
    - name: "angular-frontend-port"
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ng-frontend
status:
  loadBalancer: {}


