apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ng-frontend
  name: ng-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-frontend
  template:
    metadata:
      labels:
        app: ng-frontend
    spec:
      containers:
        - name: ng-frontend
          image: stmum0107/ngclient:v3
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
